version: '3.1'

services:
  db-codon:
    image: mysql:latest
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: cd-db-codon

  db-users:
    image: mysql:latest
    restart: always
    volumes: 
      - ./db/mysql_users:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USERS_ROOT_PASSWORD}
    container_name: cd-db-users

  myadmin-codon:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db-codon:
        condition: service_started
    restart: always
    links: 
      - db-codon
    environment:
      PMA_HOST: db-codon
    ports:
      - 8086:80
    container_name: cd-myadmin-codon

  myadmin_users:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db-users:
        condition: service_started
    restart: always
    links: 
      - db-users
    environment:
      PMA_HOST: db-users
    ports:
      - 8087:80
    container_name: cd-codon-users
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
    container_name: cd-mongo-codon